# ===----------------------------------------------------------------------=== #
# Copyright (c) 2025, Modular Inc. All rights reserved.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions:
# https://llvm.org/LICENSE.txt
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from __future__ import annotations

import inspect
import json
import logging
import time
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from pathlib import Path
from types import SimpleNamespace
from typing import Any, cast

import numpy as np
from max._core.engine import Model
from max.driver import CPU, Device, Tensor as DriverTensor
from max.dtype import DType
from max.engine.api import InferenceSession
from max.experimental import functional as F
from max.experimental import random
from max.experimental.tensor import Tensor
from max.graph import DeviceRef, Graph, TensorType
from max.graph.weights import (
    SafetensorWeights,
    WeightData,
    Weights,
    WeightsAdapter,
)
from max.nn import ReturnLogits
from max.nn.kv_cache import KVCacheInputs, PagedCacheValues
from max.nn.module_v3 import Module
from max.pipelines.architectures.qwen3.qwen3 import Qwen3
from max.pipelines.core import TextContext
from max.pipelines.lib import (
    ModelInputs,
    ModelOutputs,
    PipelineConfig,
    PipelineModel,
    SupportedEncoding,
)
from tqdm.auto import tqdm
from transformers import AutoConfig

from .model_config import ZImageConfig
from .nn.autoencoder_kl import AutoencoderKL
from .nn.image_processor import VaeImageProcessor
from .nn.transformer_z_image import ZImageTransformer2DModel
from .scheduling_flow_match_euler_discrete import (
    FlowMatchEulerDiscreteScheduler,
)
from .z_image import ZImage

logger = logging.getLogger("max.pipelines")


@dataclass(eq=False)
class ZImageInputs(ModelInputs):
    """A class representing inputs for the Z-Image model.

    This class encapsulates the input tensors required for the Z-Image model execution,
    including both text and vision inputs. Vision inputs are optional and can be None
    for text-only processing."""

    prompt: str | list[str] = None
    """ The prompt or prompts to guide the image generation. If not defined, one has to pass `prompt_embeds` instead."""

    height: int | None = None
    """ The height in pixels of the generated image."""

    width: int | None = None
    """ The width in pixels of the generated image."""

    num_inference_steps: int = 50
    """ The number of denoising steps. More denoising steps usually lead to a higher quality image at the
    expense of slower inference."""

    sigmas: list[float] | None = None
    """ Custom sigmas to use for the denoising process with schedulers which support a `sigmas` argument in
    their `set_timesteps` method. If not defined, the default behavior when `num_inference_steps` is passed
    will be used."""

    guidance_scale: float = 0.0
    """ Guidance scale as defined in Classifier-Free Diffusion Guidance.
    Higher values encourage images closely linked to the prompt, usually at the expense of lower image quality."""

    cfg_normalization: bool = False
    """ Whether to apply configuration normalization."""

    cfg_truncation: float = 1.0
    """ The truncation value for configuration."""

    negative_prompt: str | list[str] | None = None
    """ The prompt or prompts not to guide the image generation. If not defined, one has to pass
    `negative_prompt_embeds` instead. Ignored when not using guidance (i.e., ignored if `guidance_scale` is
    less than `1`)."""

    num_images_per_prompt: int | None = 1
    """ The number of images to generate per prompt."""

    seed: int | None = 0
    """ Seed for the random number generator to make generation deterministic.
    If None, random seed is used. Equivalent to torch.Generator().manual_seed(seed).
    """

    latents: Tensor | None = None
    """ Pre-generated noisy latents, sampled from a Gaussian distribution, to be used as inputs for image
    generation. Can be used to tweak the same generation with different prompts. If not provided, a latents
    tensor will be generated by sampling using the supplied random `generator`."""

    prompt_embeds: list[Tensor] | None = None
    """ Pre-generated text embeddings. Can be used to easily tweak text inputs, *e.g.* prompt weighting. If not
    provided, text embeddings will be generated from `prompt` input argument."""

    negative_prompt_embeds: list[Tensor] | None = None
    """ Pre-generated negative text embeddings. Can be used to easily tweak text inputs, *e.g.* prompt
    weighting. If not provided, negative_prompt_embeds will be generated from `negative_prompt` input argument."""

    output_type: str | None = "pil"
    """ The output format of the generate image. Choose between
    [PIL](https://pillow.readthedocs.io/en/stable/): `PIL.Image.Image` or `np.array`."""
    joint_attention_kwargs: dict[str, Any] | None = None
    """ A kwargs dictionary that if specified is passed along to the `AttentionProcessor` as defined under
    `self.processor` in [diffusers.models.attention_processor](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/attention_processor.py)."""

    callback_on_step_end: Callable[[int, int, dict], None] | None = None
    """ A function that calls at the end of each denoising steps during the inference. The function is called
    with the following arguments: `callback_on_step_end(self: DiffusionPipeline, step: int, timestep: int,
    callback_kwargs: Dict)`. `callback_kwargs` will include a list of all tensors as specified by
    `callback_on_step_end_tensor_inputs`."""

    callback_on_step_end_tensor_inputs: tuple[str] = "latents"
    """ Tuple of tensors to be included in the `callback_kwargs` dictionary."""

    max_sequence_length: int = 512
    """ The maximum sequence length for the input sequence."""

    # signal_buffers: list[Tensor]
    """Device buffers used for synchronization in communication collectives."""

    cu_seqlens: list[Tensor] | None = None
    """Cumulative sequence lengths for full attention."""

    max_seqlen: list[Tensor] | None = None
    """Maximum sequence length for full attention for vision inputs."""


def debug_tensor_to_numpy(t, name="tensor"):
    """Convert MAX tensor to numpy for debugging.

    Handles:
    - Lazy/symbolic tensors (forces realization)
    - GPU tensors (transfers to CPU for DLPack)
    - Different tensor types (experimental.Tensor vs driver.Tensor)

    Returns numpy array or None if conversion fails.
    """
    try:
        import numpy as np

        # Check if symbolic (lazy) and force realization
        if hasattr(t, 'real') and not t.real:
            print(f"DEBUG {name}: Tensor is lazy, forcing realization...")
            t._sync_realize()

        # Transfer from GPU to CPU for DLPack compatibility
        if hasattr(t, 'to'):
            t_cpu = t.to(CPU())
        else:
            t_cpu = t

        # Convert to numpy via DLPack or driver_tensor
        if hasattr(t_cpu, '__dlpack__'):
            return np.from_dlpack(t_cpu)
        elif hasattr(t_cpu, 'driver_tensor'):
            return t_cpu.driver_tensor.to_numpy()
        elif hasattr(t_cpu, 'to_numpy'):
            return t_cpu.to_numpy()
        else:
            raise AttributeError(f"Unknown tensor type: {type(t_cpu)}")
    except Exception as e:
        print(f"DEBUG {name}: Cannot convert to numpy - {e}")
        return None


def is_symbolic(t) -> bool:
    """Check if a MAX tensor is symbolic (not yet realized)."""
    if hasattr(t, 'real'):
        return not t.real
    if hasattr(t, 'storage'):
        return t.storage is None
    return False


def calculate_shift(
    image_seq_len: int,
    base_seq_len: int = 256,
    max_seq_len: int = 4096,
    base_shift: float = 0.5,
    max_shift: float = 1.15,
) -> float:
    m = (max_shift - base_shift) / (max_seq_len - base_seq_len)
    b = base_shift - m * base_seq_len
    mu = image_seq_len * m + b
    return mu


def retrieve_timesteps(
    scheduler: SchedulerMixin,
    num_inference_steps: int | None = None,
    device: str | Device | None = None,
    timesteps: list[int] | None = None,
    sigmas: list[float] | None = None,
    **kwargs,
) -> tuple[Tensor, int]:
    r"""
    Calls the scheduler's `set_timesteps` method and retrieves timesteps from the scheduler after the call. Handles
    custom timesteps. Any kwargs will be supplied to `scheduler.set_timesteps`.

    Args:
        scheduler (`SchedulerMixin`):
            The scheduler to get timesteps from.
        num_inference_steps (`int`):
            The number of diffusion steps used when generating samples with a pre-trained model. If used, `timesteps`
            must be `None`.
        device (`str` or `Device`, *optional*):
            The device to which the timesteps should be moved to. If `None`, the timesteps are not moved.
        timesteps (`list[int]`, *optional*):
            Custom timesteps used to override the timestep spacing strategy of the scheduler. If `timesteps` is passed,
            `num_inference_steps` and `sigmas` must be `None`.
        sigmas (`list[float]`, *optional*):
            Custom sigmas used to override the timestep spacing strategy of the scheduler. If `sigmas` is passed,
            `num_inference_steps` and `timesteps` must be `None`.

    Returns:
        `Tuple[Tensor, int]`: A tuple where the first element is the timestep schedule from the scheduler and the
        second element is the number of inference steps.
    """
    if timesteps is not None and sigmas is not None:
        raise ValueError(
            "Only one of `timesteps` or `sigmas` can be passed. Please choose one to set custom values"
        )
    if timesteps is not None:
        accepts_timesteps = "timesteps" in set(
            inspect.signature(scheduler.set_timesteps).parameters.keys()
        )
        if not accepts_timesteps:
            raise ValueError(
                f"The current scheduler class {scheduler.__class__}'s `set_timesteps` does not support custom"
                f" timestep schedules. Please check whether you are using the correct scheduler."
            )
        scheduler.set_timesteps(timesteps=timesteps, device=device, **kwargs)
        timesteps = scheduler.timesteps
        num_inference_steps = len(timesteps)
    elif sigmas is not None:
        accept_sigmas = "sigmas" in set(
            inspect.signature(scheduler.set_timesteps).parameters.keys()
        )
        if not accept_sigmas:
            raise ValueError(
                f"The current scheduler class {scheduler.__class__}'s `set_timesteps` does not support custom"
                f" sigmas schedules. Please check whether you are using the correct scheduler."
            )
        scheduler.set_timesteps(sigmas=sigmas, device=device, **kwargs)
        timesteps = scheduler.timesteps
        num_inference_steps = len(timesteps)
    else:
        scheduler.set_timesteps(num_inference_steps, device=device, **kwargs)
        timesteps = scheduler.timesteps
    return timesteps, num_inference_steps


class ZImageModel(
    # AlwaysSignalBuffersMixin,
    PipelineModel[TextContext],
):
    """A ZImage model for text-to-image generation."""

    scheduler: FlowMatchEulerDiscreteScheduler
    """The scheduler to be used for image generation."""

    vae: AutoencoderKL
    """The VAE to be used for image generation."""

    text_encoder: Qwen3
    """The text encoder to be used for image generation."""

    transformer: ZImageTransformer2DModel
    """The transformer to be used for image generation."""

    model_config: ZImageConfig | None
    """The ZImage model configuration."""

    _input_row_offsets_prealloc: list[Tensor]
    """Pre-allocated per-device tensors for input row offsets in multi-step execution."""

    def __init__(
        self,
        pipeline_config: PipelineConfig,
        session: InferenceSession,
        huggingface_config: AutoConfig,
        encoding: SupportedEncoding,
        devices: list[Device],
        kv_cache_config: KVCacheConfig,
        weights: Weights,
        adapter: WeightsAdapter | None = None,
        return_logits: ReturnLogits = ReturnLogits.LAST_TOKEN,
    ):
        super().__init__(
            pipeline_config,
            session,
            huggingface_config,
            encoding,
            devices,
            kv_cache_config,
            weights,
            adapter,
            return_logits,
        )

        # For Z-Image, the Hugging Face repository is a diffusers pipeline with
        # separate subfolders for scheduler, VAE, transformer, and text_encoder.
        # The base PipelineModel only knows about the main huggingface_config
        # (the text encoder). Here we explicitly load the configs for the
        # scheduler, VAE, and transformer components so ZImageConfig.generate
        # can build the full MAX configuration.

        model_config = self.pipeline_config.model_config
        repo_id = model_config.model_path
        model_revision = model_config.huggingface_model_revision
        trust_remote_code = model_config.trust_remote_code

        # Scheduler config is a diffusers-style `scheduler_config.json` that is
        # not a standard Transformers model config (no `model_type` field).
        # Load it directly as JSON and wrap it in a SimpleNamespace so
        # SchedulerConfig.generate can access attributes.
        from huggingface_hub import hf_hub_download

        scheduler_config_path = hf_hub_download(
            repo_id,
            filename="scheduler/scheduler_config.json",
            revision=model_revision,
        )
        with open(scheduler_config_path, encoding="utf-8") as f:
            scheduler_dict = json.load(f)
        self.scheduler_config = SimpleNamespace(**scheduler_dict)

        # VAE and transformer are also diffusers components with their own
        # `config.json` files that are not standard Transformers model configs
        # (no `model_type`). Load them similarly via JSON.
        vae_config_path = hf_hub_download(
            repo_id,
            filename="vae/config.json",
            revision=model_revision,
        )
        with open(vae_config_path, encoding="utf-8") as f:
            vae_dict = json.load(f)
        self.vae_config = SimpleNamespace(**vae_dict)

        self.text_encoder_config = AutoConfig.from_pretrained(
            repo_id,
            subfolder="text_encoder",
            revision=model_revision,
            trust_remote_code=trust_remote_code,
        )

        transformer_config_path = hf_hub_download(
            repo_id,
            filename="transformer/config.json",
            revision=model_revision,
        )
        with open(transformer_config_path, encoding="utf-8") as f:
            transformer_dict = json.load(f)
        self.transformer_config = SimpleNamespace(**transformer_dict)

        self.model_config = None
        self._session = session  # reuse for on-device casts

        self.scheduler = None
        self.vae.decoder, self.text_encoder, self.transformer = self.load_model(
            session
        )
        # Use uncompiled transformer for debugging NaN issues
        # self.transformer = self.model.transformer

        # Access config from vae instance or config object
        self.vae_scale_factor = 2 ** (
            len(self.model_config.vae_config.block_out_channels) - 1
        )
        self.image_processor = VaeImageProcessor()

        # Serving interface: image_pipeline is self
        self._active_requests: dict[str, Any] = {}

    @property
    def image_pipeline(self) -> ZImageModel:
        """Returns self for ImageGeneratorPipeline compatibility."""
        return self

    @classmethod
    def calculate_max_seq_len(
        cls, pipeline_config: PipelineConfig, huggingface_config: AutoConfig
    ) -> int:
        """Calculate the optimal max sequence length for the model."""
        # For Z-Image, this might be fixed or configurable.
        # Returning a safe default for now, similar to other vision models.
        return 4096

    @classmethod
    def get_num_layers(cls, huggingface_config: AutoConfig) -> int:
        """Gets the number of hidden layers from the HuggingFace configuration."""
        if huggingface_config is None:
            # If config is None (e.g. from PipelineModel init), return a safe default or 0
            # This might be used for batch size inference.
            return 0
        return ZImageConfig.get_num_layers(huggingface_config)

    def load_model(
        self, session: InferenceSession
    ) -> tuple[AutoencoderKL, Model, ZImageTransformer2DModel]:
        """Loads the compiled Z-Image model into the MAX Engine session.

        Args:
            session: The MAX Engine inference session.

        Returns:
            The loaded MAX Engine model object.
        """
        if self.pipeline_config.max_batch_size is None:
            raise ValueError("Expected max_batch_size to be set")
        self._input_row_offsets_prealloc = F.range(
            0,
            self.pipeline_config.max_batch_size + 1,
            dtype=DType.uint32,
            device=self.devices[0],
        )

        logger.info("Building and compiling the whole pipeline...")
        before = time.perf_counter()

        if not isinstance(self.weights, SafetensorWeights):
            raise ValueError(
                "ZImage currently only supports safetensors weights"
            )

        # Partition raw safetensor weights by their originating file path.
        # This lets us treat diffusers-style folders (vae/, text_encoder/, transformer/)
        # as separate components without relying on key-name heuristics.
        st_weights: SafetensorWeights = self.weights
        filepaths = [Path(p) for p in st_weights._filepaths]

        vae_weights: dict[str, Weights] = {}
        text_encoder_weights: dict[str, Weights] = {}
        transformer_weights: dict[str, Weights] = {}

        for key, weight in st_weights.items():
            file_idx = st_weights._tensors_to_file_idx[key]
            filepath = filepaths[file_idx]
            parts = set(filepath.parts)

            if "vae" in parts:
                vae_weights[key] = weight
            elif "text_encoder" in parts:
                text_encoder_weights[key] = weight
            elif "transformer" in parts:
                transformer_weights[key] = weight
            else:
                logger.debug(
                    "Unrecognized Z-Image weight file '%s' for key '%s', assigning to transformer",
                    filepath,
                    key,
                )
                transformer_weights[key] = weight

        # Materialize VAE and transformer weights directly.
        vae_state_dict: dict[str, WeightData] = {
            key: weight.data() for key, weight in vae_weights.items()
        }
        transformer_state_dict: dict[str, WeightData] = {
            key: weight.data() for key, weight in transformer_weights.items()
        }

        # Apply the architecture weight adapter (if any) only to the text encoder
        # subset. For Z-Image this maps Qwen3-VL style names to the expected
        # ? format.
        if self.adapter:
            text_encoder_llm_state_dict: dict[str, WeightData] = self.adapter(
                text_encoder_weights,
                huggingface_config=self.huggingface_config,
                pipeline_config=self.pipeline_config,
            )
        else:
            text_encoder_llm_state_dict = {
                key: weight.data()
                for key, weight in text_encoder_weights.items()
            }

        text_encoder_state_dict: dict[str, dict[str, WeightData]] = {
            "llm_state_dict": text_encoder_llm_state_dict,
        }

        # Generate ZImage config from HuggingFace config
        zimage_config = ZImageConfig.generate(
            pipeline_config=self.pipeline_config,
            scheduler_config=self.scheduler_config,
            vae_config=self.vae_config,
            text_encoder_config=self.text_encoder_config,
            transformer_config=self.transformer_config,
            vae_state_dict=vae_state_dict,
            text_encoder_state_dict=text_encoder_state_dict,
            transformer_state_dict=transformer_state_dict,
            dtype=self.dtype,
            n_devices=len(self.devices),
            cache_dtype=self.encoding.cache_dtype,
            kv_cache_config=self.kv_cache_config,
            return_logits=self.return_logits,
        )
        self.model_config = zimage_config

        if self.model_config is None:
            raise ValueError("Model config must be initialized")

        # Instantiate ZImage container to build sub-models
        # Pass device for RoPE embedding precomputation on GPU
        device0 = self.devices[0]
        self.model: Module = ZImage(self.model_config, device=device0)

        graph_inputs = self.model.text_encoder.input_types(
            self.model.text_encoder.kv_params
        )
        # self.model.text_encoder.load_state_dict(
        #     text_encoder_llm_state_dict,
        #     override_quantization_encoding=True,
        #     weight_alignment=1,
        #     # Stops strict from raising error when sharing LM head weights
        #     # (as LM head is never technically loaded from the state dict)
        #     strict=(
        #         not getattr(
        #             self.huggingface_config, "tie_word_embeddings", False
        #         )
        #     ),
        # )
        device0 = self.devices[0]

        self.model.to(device0)
        device_ref = DeviceRef(device0.label, device0.id)
        sample_type = TensorType(
            DType.bfloat16, shape=(1, 16, 128, 128), device=device_ref
        )

        # Strip 'decoder.' prefix from VAE weights for the Decoder module.
        # The safetensors file has keys like 'decoder.conv_in.weight' but the
        # Decoder module's parameters are named 'conv_in.weight'.
        decoder_weights: dict[str, WeightData] = {
            key.removeprefix("decoder."): value
            for key, value in vae_state_dict.items()
            if key.startswith("decoder.")
        }

        self.vae = self.model.vae
        # Ensure decoder is set correctly for uncompiled use
        self.vae.decoder = self.model.vae.decoder
        self.scheduler = self.model.scheduler

        # Load weights into the uncompiled models
        # self.model.transformer.load_state_dict(transformer_state_dict)
        # self.model.vae.decoder.load_state_dict(decoder_weights)

        # # Move to device for uncompiled execution
        # self.model.transformer.to(self.devices[0])
        # self.model.vae.decoder.to(self.devices[0])

        logger.info("Building and compiling VAE's decoder...")
        before_vae_decode_build = time.perf_counter()
        compiled_vae_decoder_model = self.model.vae.decoder.compile(
            sample_type,
            weights=decoder_weights,
        )
        after_vae_decode_build = time.perf_counter()
        logger.info(
            f"Building and compiling VAE's decoder took {after_vae_decode_build - before_vae_decode_build:.6f} seconds"
        )

        C, F_dim, H_dim, W_dim = 16, 1, 128, 128
        cap_seq_len = 75

        hidden_states_type = TensorType(
            DType.bfloat16, shape=(C, F_dim, H_dim, W_dim), device=device_ref
        )
        t_type = TensorType(DType.float32, shape=(1,), device=device_ref)
        cap_feats_type = TensorType(
            DType.bfloat16, shape=(cap_seq_len, 2560), device=device_ref
        )

        logger.info("Building and compiling the backbone transformer...")
        before_transformer_build = time.perf_counter()
        compiled_transformer_model = self.model.transformer.compile(
            hidden_states_type,
            t_type,
            cap_feats_type,
            weights=transformer_state_dict,
        )
        after_transformer_build = time.perf_counter()
        logger.info(
            f"Building and compiling the backbone transformer took {after_transformer_build - before_transformer_build:.6f} seconds"
        )

        # logger.info("Building and compiling text encoder...")
        # before_text_encoder_build = time.perf_counter()
        # text_encoder_graph = self._build_text_encoder_graph(graph_inputs)
        # after_text_encoder_build = time.perf_counter()

        # logger.info(
        #     f"Building text encoder's graph took {after_text_encoder_build - before_text_encoder_build:.6f} seconds"
        # )

        # before_text_encoder_compile = time.perf_counter()
        # compiled_text_encoder_model = session.load(
        #     text_encoder_graph,
        #     weights_registry=text_encoder_llm_state_dict,
        # )
        after = time.perf_counter()

        # logger.info(
        #     f"Compiling text encoder's model took {after - before_text_encoder_compile:.6f} seconds"
        # )
        logger.info(
            f"Building and compiling the whole pipeline took {after - before:.6f} seconds"
        )
        return (
            compiled_vae_decoder_model,
            None,  # compiled_text_encoder_model,
            compiled_transformer_model,
        )

    def _build_text_encoder_graph(
        self, graph_inputs: tuple[TensorType, ...]
    ) -> Graph:
        """Build the MAX graph for the text encoder.

        Uses native Qwen3 with return_hidden_states=SECOND_TO_LAST configured in
        model_config.py. SECOND_TO_LAST returns the second-to-last layer's hidden
        states directly (matching diffusers' hidden_states[-2] pattern).

        Args:
            graph_inputs: Tuple of TensorType defining the graph inputs.

        Returns:
            Compiled MAX graph that outputs hidden states of shape
            (seq_len, hidden_size) from the second-to-last layer.
        """
        with Graph("qwen3_text_encoder", input_types=graph_inputs) as graph:
            tokens, input_row_offsets, return_n_logits, *kv_cache_inputs = (
                graph.inputs
            )
            kv_collection = PagedCacheValues(
                kv_blocks=kv_cache_inputs[0].buffer,
                cache_lengths=kv_cache_inputs[1].tensor,
                lookup_table=kv_cache_inputs[2].tensor,
                max_lengths=kv_cache_inputs[3].tensor,
            )
            # Qwen3 with ReturnHiddenStates.SECOND_TO_LAST returns
            # (logits, second_to_last_hidden_states) directly
            outputs = self.text_encoder(
                tokens.tensor,
                kv_collection,
                return_n_logits.tensor,
                input_row_offsets.tensor,
            )
            # Extract second-to-last hidden states (last element of output tuple)
            # Shape: (seq_len, hidden_size)
            hidden_states = outputs[-1]
            graph.output(hidden_states)
            return graph

    def encode_prompt(
        self,
        prompt: str | list[str],
        device: Device | None = None,
        do_classifier_free_guidance: bool = True,
        negative_prompt: str | list[str] | None = None,
        prompt_embeds: list[Tensor] | None = None,
        negative_prompt_embeds: Tensor | None = None,
        max_sequence_length: int = 512,
    ) -> tuple[list[Tensor], list[Tensor]]:
        prompt = [prompt] if isinstance(prompt, str) else prompt
        prompt_embeds = self._encode_prompt(
            prompt,
            device,
            prompt_embeds,
            max_sequence_length,
        )

        if do_classifier_free_guidance:
            if negative_prompt is None:
                negative_prompt = ["" for _ in prompt]
            else:
                negative_prompt = (
                    [negative_prompt]
                    if isinstance(negative_prompt, str)
                    else negative_prompt
                )
            if len(prompt) != len(negative_prompt):
                raise ValueError(
                    "The lists of prompt and negative prompt must have the same length"
                )
            negative_prompt_embeds = self._encode_prompt(
                negative_prompt,
                device,
                negative_prompt_embeds,
                max_sequence_length,
            )
        else:
            negative_prompt_embeds = []
        return prompt_embeds, negative_prompt_embeds

    def _encode_prompt(
        self,
        prompt: str | list[str],
        device: Device | None = None,
        prompt_embeds: list[Tensor] | None = None,
        max_sequence_length: int = 512,
    ) -> list[Tensor]:
        device = device or self._execution_device

        if prompt_embeds is not None:
            return prompt_embeds

            if isinstance(prompt, str):
                prompt = [prompt]

            for i, prompt_item in enumerate(prompt):
                messages = [
                    {"role": "user", "content": prompt_item},
                ]
                prompt_item = self.tokenizer.apply_chat_template(
                    messages,
                    tokenize=False,
                    add_generation_prompt=True,
                    enable_thinking=True,
                )
                prompt[i] = prompt_item

            text_inputs = self.tokenizer(
                prompt,
                # padding="max_length",
                # max_length=max_sequence_length,
                truncation=True,
                # return_tensors="pt",
            )

            text_input_ids = text_inputs.input_ids.to(device)
            prompt_masks = text_inputs.attention_mask.to(device).bool()

        prompt_embeds = self.text_encoder(
            input_ids=text_input_ids,
            attention_mask=prompt_masks,
            output_hidden_states=True,
        ).hidden_states[-2]

        embeddings_list = []

        for i in range(len(prompt_embeds)):
            embeddings_list.append(prompt_embeds[i][prompt_masks[i]])

        return embeddings_list

    def prepare_latents(
        self,
        batch_size: int,
        num_channels_latents: int,
        height: int,
        width: int,
        dtype: DType,
        device: Device,
        seed: int | None = None,
        latents: Tensor | None = None,
    ) -> Tensor:
        """Prepare latents for the diffusion process.

        Args:
            batch_size: Number of images to generate.
            num_channels_latents: Number of channels in the latent space.
            height: Target image height.
            width: Target image width.
            dtype: Data type for the latents.
            device: Device to place the latents on.
            seed: Optional seed for reproducible random generation.
                If None, uses random seed (non-deterministic).
            latents: Optional pre-generated latents to use instead.

        Returns:
            Latent tensor of shape (batch_size, num_channels_latents, height, width).
        """
        import torch

        height = 2 * (int(height) // (self.vae_scale_factor * 2))
        width = 2 * (int(width) // (self.vae_scale_factor * 2))

        shape = (batch_size, num_channels_latents, height, width)

        if latents is None:
            # Use PyTorch for random generation to match diffusers exactly
            # This ensures identical results when using the same seed
            generator = torch.Generator("cpu")
            if seed is not None:
                generator.manual_seed(seed)
            latents_torch = torch.randn(shape, generator=generator, dtype=torch.float32)
            # Convert to MAX tensor and move to device
            latents = Tensor.from_dlpack(latents_torch.numpy()).to(device)
        else:
            if latents.shape != shape:
                raise ValueError(
                    f"Unexpected latents shape, got {latents.shape}, expected {shape}"
                )
            latents = latents.to(device)
        return latents

    @property
    def guidance_scale(self) -> float:
        return self._guidance_scale

    @property
    def do_classifier_free_guidance(self) -> bool:
        return self._guidance_scale > 1

    @property
    def joint_attention_kwargs(self) -> dict[str, Any] | None:
        return self._joint_attention_kwargs

    @property
    def num_timesteps(self) -> int:
        return self._num_timesteps

    @property
    def interrupt(self) -> Callable[[Tensor], bool] | None:
        return self._interrupt

    def progress_bar(self, total: int) -> tqdm:
        return tqdm(total=total)

    def execute(
        self,
        model_inputs: ModelInputs,
    ) -> ModelOutputs:
        r"""
        Executes the Z-Image model with the prepared inputs.

        Args:
            model_inputs: A ZImageInputs instance containing all image generation parameters
                including prompt, dimensions, guidance scale, etc.

        Returns:
            ModelOutputs containing the generated images.
        """
        # Use cast for type safety (same pattern as GptOssModel)
        model_inputs = cast(ZImageInputs, model_inputs)

        # Extract parameters from model_inputs
        prompt = model_inputs.prompt
        height = model_inputs.height or 1024
        width = model_inputs.width or 1024
        num_inference_steps = model_inputs.num_inference_steps
        sigmas = model_inputs.sigmas
        guidance_scale = model_inputs.guidance_scale
        cfg_normalization = model_inputs.cfg_normalization
        cfg_truncation = model_inputs.cfg_truncation
        negative_prompt = model_inputs.negative_prompt
        num_images_per_prompt = model_inputs.num_images_per_prompt or 1
        latents = model_inputs.latents
        prompt_embeds = model_inputs.prompt_embeds
        negative_prompt_embeds = model_inputs.negative_prompt_embeds
        output_type = model_inputs.output_type
        joint_attention_kwargs = model_inputs.joint_attention_kwargs
        callback_on_step_end = model_inputs.callback_on_step_end
        callback_on_step_end_tensor_inputs = (
            model_inputs.callback_on_step_end_tensor_inputs
        )
        max_sequence_length = model_inputs.max_sequence_length
        cu_seqlens = model_inputs.cu_seqlens
        max_seqlen = model_inputs.max_seqlen

        vae_scale = self.vae_scale_factor * 2
        if height % vae_scale != 0:
            raise ValueError(
                f"Height must be divisible by {vae_scale} (got {height}). "
                f"Please adjust the height to a multiple of {vae_scale}."
            )
        if width % vae_scale != 0:
            raise ValueError(
                f"Width must be divisible by {vae_scale} (got {width}). "
                f"Please adjust the width to a multiple of {vae_scale}."
            )

        device = self.devices[0]

        self._guidance_scale = guidance_scale
        self._joint_attention_kwargs = joint_attention_kwargs
        self._interrupt = False
        self._cfg_normalization = cfg_normalization
        self._cfg_truncation = cfg_truncation
        # 2. Define call parameters
        if prompt is not None and isinstance(prompt, str):
            batch_size = 1
        elif prompt is not None and isinstance(prompt, list):
            batch_size = len(prompt)
        else:
            batch_size = len(prompt_embeds)

        # If prompt_embeds is provided and prompt is None, skip encoding
        if prompt_embeds is not None and prompt is None:
            if (
                self.do_classifier_free_guidance
                and negative_prompt_embeds is None
            ):
                raise ValueError(
                    "When `prompt_embeds` is provided without `prompt`, "
                    "`negative_prompt_embeds` must also be provided for classifier-free guidance."
                )
        # else:
        #     (
        #         prompt_embeds,
        #         negative_prompt_embeds,
        #     ) = self.encode_prompt(
        #         prompt=prompt,
        #         negative_prompt=negative_prompt,
        #         do_classifier_free_guidance=self.do_classifier_free_guidance,
        #         prompt_embeds=prompt_embeds,
        #         negative_prompt_embeds=negative_prompt_embeds,
        #         device=device,
        #         max_sequence_length=max_sequence_length,
        #     )
        from safetensors.torch import load_file

        # Load prompt embeddings from safetensors file
        # Note: This is temporary! The text encoder should be used instead.
        data = load_file("/root/prompt_embeds.safetensors")
        prompt_embeds_torch = data["prompt_embeds"]
        # print(f"DEBUG: Loaded prompt_embeds shape: {prompt_embeds_torch.shape}, dtype: {prompt_embeds_torch.dtype}")
        # Convert torch -> numpy -> MAX tensor
        # NumPy doesn't support bfloat16, so convert to float32 first
        prompt_embeds_np = prompt_embeds_torch.float().numpy()  # bfloat16 -> float32 -> numpy
        prompt_embeds = Tensor.from_dlpack(prompt_embeds_np).to(device).cast(DType.bfloat16)

        # CRITICAL: Validate prompt_embeds shape matches compiled model expectation
        expected_cap_seq_len = 75
        expected_hidden_dim = 2560
        actual_shape = tuple(prompt_embeds.shape)
        # if actual_shape != (expected_cap_seq_len, expected_hidden_dim):
        #     print(f"WARNING: prompt_embeds shape {actual_shape} != expected ({expected_cap_seq_len}, {expected_hidden_dim})")
        #     print(f"         This WILL cause garbage output from the compiled transformer!")

        # 4. Prepare latent variables
        num_channels_latents = self.transformer.in_channels

        # Extract seed for reproducible latent generation
        seed = model_inputs.seed

        latents = self.prepare_latents(
            batch_size * num_images_per_prompt,
            num_channels_latents,
            height,
            width,
            DType.float32,
            device,
            seed=seed,
            latents=latents,
        )

        # DEBUG: Check initial latents
        from max.driver import CPU
        # latents_init_np = np.from_dlpack(latents.to(CPU()))
        # print(f"DEBUG: Initial latents - shape: {latents_init_np.shape}, "
        #       f"min: {np.nanmin(latents_init_np):.4f}, max: {np.nanmax(latents_init_np):.4f}, "
        #       f"nan: {np.isnan(latents_init_np).any()}")

        # Repeat prompt_embeds for num_images_per_prompt
        if num_images_per_prompt > 1:
            prompt_embeds = [
                pe for pe in prompt_embeds for _ in range(num_images_per_prompt)
            ]
            if self.do_classifier_free_guidance and negative_prompt_embeds:
                negative_prompt_embeds = [
                    npe
                    for npe in negative_prompt_embeds
                    for _ in range(num_images_per_prompt)
                ]

        actual_batch_size = batch_size * num_images_per_prompt
        image_seq_len = (int(latents.shape[2]) // 2) * (
            int(latents.shape[3]) // 2
        )

        # 5. Prepare timesteps
        mu = calculate_shift(
            image_seq_len,
            self.scheduler.base_image_seq_len,
            self.scheduler.max_image_seq_len,
            self.scheduler.base_shift,
            self.scheduler.max_shift,
        )
        self.scheduler.sigma_min = 0.0
        scheduler_kwargs = {"mu": mu}
        timesteps, num_inference_steps = retrieve_timesteps(
            self.scheduler,
            num_inference_steps,
            device,
            sigmas=sigmas,
            **scheduler_kwargs,
        )
        num_warmup_steps = max(
            int(timesteps.shape[0])
            - num_inference_steps * self.scheduler.order,
            0,
        )
        self._num_timesteps = int(timesteps.shape[0])

        print("DEBUG: Starting denoising loop")

        # Pre-set step index to avoid expensive lookup on each step
        self.scheduler._step_index = 0

        # 6. Denoising loop
        with self.progress_bar(total=num_inference_steps) as progress_bar:
            for i in range(self._num_timesteps):
                t = timesteps[i]
                if self.interrupt:
                    continue

                # broadcast to batch dimension in a way that's compatible with ONNX/Core ML
                timestep = F.broadcast_to(t, (int(latents.shape[0]),))
                timestep = (1000 - timestep) / 1000
                # Normalized time for time-aware config (0 at start, 1 at end)
                # Use loop index to avoid GPU sync from .item()
                t_norm = i / max(1, self._num_timesteps - 1)

                # Handle cfg truncation
                current_guidance_scale = self.guidance_scale
                if (
                    self.do_classifier_free_guidance
                    and self._cfg_truncation is not None
                    and float(self._cfg_truncation) <= 1
                ):
                    if t_norm > self._cfg_truncation:
                        current_guidance_scale = 0.0

                # Run CFG only if configured AND scale is non-zero
                apply_cfg = (
                    self.do_classifier_free_guidance
                    and current_guidance_scale > 0
                )

                if apply_cfg:
                    latents_typed = latents.cast(DType.bfloat16)
                    latent_model_input = latents_typed.repeat(2, 1, 1, 1)
                    prompt_embeds_model_input = (
                        prompt_embeds + negative_prompt_embeds
                    )
                    timestep_model_input = timestep.repeat(2)
                else:
                    latent_model_input = latents.cast(DType.bfloat16)
                    prompt_embeds_model_input = prompt_embeds
                    timestep_model_input = timestep

                latent_model_input = F.unsqueeze(latent_model_input, 2)

                # Debug: Check all inputs before calling compiled transformer
                x_in = F.squeeze(latent_model_input, 0)
                # if i == 0:
                #     print(f"DEBUG Step 0: Transformer inputs:")
                #     print(f"  x (latents): shape={tuple(x_in.shape)}, dtype={x_in.dtype}")
                #     print(f"  t (timestep): shape={tuple(timestep_model_input.shape)}, dtype={timestep_model_input.dtype}")
                #     print(f"  cap_feats: shape={tuple(prompt_embeds_model_input.shape)}, dtype={prompt_embeds_model_input.dtype}")
                #     print(f"Expected: x=(16, 1, 128, 128) bfloat16, t=(1,) float32, cap_feats=(75, 2560) bfloat16")

                model_out = self.transformer(
                    x_in,
                    timestep_model_input,
                    prompt_embeds_model_input,
                )

                # DEBUG: Check transformer output at first step
                # if i == 0:
                #     from max.driver import CPU
                #     # Cast to float32 before numpy conversion (numpy doesn't support bfloat16)
                #     model_out_np = np.from_dlpack(model_out.cast(DType.float32).to(CPU()))
                #     print(f"DEBUG Step 0: Transformer output - shape: {model_out_np.shape}, "
                #           f"min: {np.nanmin(model_out_np):.4f}, max: {np.nanmax(model_out_np):.4f}, "
                #           f"nan: {np.isnan(model_out_np).any()}")

                if apply_cfg:
                    # Perform CFG
                    pos_out = model_out_list[:actual_batch_size]
                    neg_out = model_out_list[actual_batch_size:]

                    noise_pred = []
                    for j in range(actual_batch_size):
                        pos = pos_out[j].cast(DType.float32)
                        neg = neg_out[j].cast(DType.float32)

                        pred = pos + current_guidance_scale * (pos - neg)

                        # Renormalization
                        if (
                            self._cfg_normalization
                            and float(self._cfg_normalization) > 0.0
                        ):
                            # ori_pos_norm = torch.linalg.vector_norm(pos)
                            # new_pos_norm = torch.linalg.vector_norm(pred)
                            ori_pos_norm = F.sqrt(F.sum(pos * pos))
                            new_pos_norm = F.sqrt(F.sum(pred * pred))
                            max_new_norm = ori_pos_norm * float(
                                self._cfg_normalization
                            )
                            if new_pos_norm > max_new_norm:
                                pred = pred * (max_new_norm / new_pos_norm)

                        noise_pred.append(pred)

                    noise_pred = F.stack(noise_pred, axis=0)
                else:
                    # model_out is a single tensor [C, F, H, W], add batch dim
                    noise_pred = F.unsqueeze(model_out.cast(DType.float32), 0)

                noise_pred = -F.squeeze(noise_pred, 2)

                # compute the previous noisy sample x_t -> x_t-1
                latents = self.scheduler.step(
                    noise_pred.cast(DType.float32),
                    t,
                    latents,
                ).prev_sample

                # DEBUG: Check latents after scheduler at first step
                # if i == 0:
                #     print(latents.shape, np.isnan(np.from_dlpack(latents.to(CPU()))).any())

                if callback_on_step_end is not None:
                    callback_kwargs = {}
                    for k in callback_on_step_end_tensor_inputs:
                        callback_kwargs[k] = locals()[k]
                    callback_outputs = callback_on_step_end(
                        self, i, t, callback_kwargs
                    )

                    latents = callback_outputs.pop("latents", latents)
                    prompt_embeds = callback_outputs.pop(
                        "prompt_embeds", prompt_embeds
                    )
                    negative_prompt_embeds = callback_outputs.pop(
                        "negative_prompt_embeds", negative_prompt_embeds
                    )

                # call the callback, if provided
                if i == int(timesteps.shape[0]) - 1 or (
                    (i + 1) > num_warmup_steps
                    and (i + 1) % self.scheduler.order == 0
                ):
                    progress_bar.update()

        if output_type == "latent":
            image = latents

        else:
            # Debug: Check final latent statistics before VAE decode
            # DISABLED - causes OOM when copying to CPU
            # from max.driver import CPU
            # latents_np = np.from_dlpack(latents.to(CPU()))
            # print(f"DEBUG: Final latents after denoising - shape: {latents_np.shape}, "
            #       f"min: {np.nanmin(latents_np):.4f}, max: {np.nanmax(latents_np):.4f}, "
            #       f"mean: {np.nanmean(latents_np):.4f}, nan: {np.isnan(latents_np).any()}")

            latents = latents.cast(DType.bfloat16)
            latents = (
                latents / self.vae.scaling_factor
            ) + self.vae.shift_factor

            # Debug: Check scaled latents (bfloat16 -> float32 for numpy)
            # DISABLED - causes OOM when copying to CPU
            # scaled_latents_np = np.from_dlpack(latents.cast(DType.float32).to(CPU()))
            # print(f"DEBUG: Scaled latents for VAE - shape: {scaled_latents_np.shape}, "
            #       f"min: {np.nanmin(scaled_latents_np):.4f}, max: {np.nanmax(scaled_latents_np):.4f}, "
            #       f"mean: {np.nanmean(scaled_latents_np):.4f}")
            # print(latents.shape, latents.dtype, F.min(latents), F.max(latents), F.mean(latents))
            image = self.vae.decoder(latents)#.sample
            # print(image.shape, image.dtype, F.min(image), F.max(image), F.mean(image))

            # Debug: Check VAE output (cast to float32 for numpy if needed)
            # DISABLED - causes OOM when copying to CPU
            # image_np = np.from_dlpack(image.cast(DType.float32).to(CPU()))
            # print(f"DEBUG: VAE output - shape: {image_np.shape}, "
            #       f"min: {np.nanmin(image_np):.4f}, max: {np.nanmax(image_np):.4f}, "
            #       f"mean: {np.nanmean(image_np):.4f}")

        # Offload all models
        # self.maybe_free_model_hooks()

        return ModelOutputs(hidden_states=cast(DriverTensor, image.driver_tensor), logits=None)

    def prepare_initial_token_inputs(
        self,
        replica_batches: Sequence[Sequence[TextContext]],
        kv_cache_inputs: KVCacheInputs | None = None,
        return_n_logits: int = 1,
    ) -> ModelInputs:
        """Prepares the initial inputs for the first execution pass of the GPT OSS model.

        Args:
            replica_batches: A sequence of sequences of :obj:`TextContext` objects representing
                the input prompts for each replica.
            kv_cache_inputs: Optional inputs required by the KV cache manager.

        Returns:
            The prepared :obj:`ModelInputs` object for the initial execution step.
        """
        if len(replica_batches) > 1:
            raise ValueError("Model does not support DP>1")

        context_batch = replica_batches[0]
        assert kv_cache_inputs is not None
        kv_cache_inputs = cast(KVCacheInputsSequence, kv_cache_inputs)

        # This needs to be replaced with actual input preparation
        # Get input_row_offsets: start and end position of each batch in the
        # combined total_seq_len dimension.
        input_row_offsets = np.cumsum(
            [0] + [ctx.active_length for ctx in context_batch], dtype=np.uint32
        )

        # Create a ragged token vector of length: sum(len(t) for t in tokens).
        tokens = np.concatenate([ctx.next_tokens for ctx in context_batch])

        # Create input_row_offsets
        input_row_offsets_tensor = Tensor.from_numpy(input_row_offsets).to(
            self.devices[0]
        )

        return GptOssInputs(
            tokens=Tensor.from_numpy(tokens).to(self.devices[0]),
            input_row_offsets=input_row_offsets_tensor,
            return_n_logits=Tensor.from_numpy(
                np.array([return_n_logits], dtype=np.int64)
            ),
            kv_cache_inputs=kv_cache_inputs,
        )

    def prepare_next_token_inputs(
        self, next_tokens: Tensor, prev_model_inputs: ModelInputs
    ) -> ModelInputs:
        """Prepares the inputs for subsequent execution steps in a multi-step generation.

        Args:
            next_tokens: The tensor containing the token IDs generated in the previous step.
            prev_model_inputs: The :obj:`ModelInputs` used in the previous execution step.

        Returns:
            The prepared :obj:`ModelInputs` object for the next execution step.
        """
        prev_model_inputs = cast(GptOssInputs, prev_model_inputs)
        row_offsets_size = prev_model_inputs.input_row_offsets.shape[0]

        next_row_offsets = self._input_row_offsets_prealloc[
            :row_offsets_size
        ].to(self.devices[0])

        return GptOssInputs(
            tokens=next_tokens,
            input_row_offsets=next_row_offsets,
            return_n_logits=prev_model_inputs.return_n_logits,
            kv_cache_inputs=prev_model_inputs.kv_cache_inputs,
        )
