# ===----------------------------------------------------------------------=== #
# Copyright (c) 2025, Modular Inc. All rights reserved.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions:
# https://llvm.org/LICENSE.txt
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===----------------------------------------------------------------------=== #

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

from typing import Iterable, Sequence, Tuple
import grpc
from max.serve.kvcache_agent import (
    kvcache_agent_service_v1_pb2 as max_dot_serve_dot_kvcache__agent_dot_kvcache__agent__service__v1__pb2,
)

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in max/serve/kvcache_agent/kvcache_agent_service_v1_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class KVCacheAgentServiceStub:
    """Service that exposes the KV Cache Agent state"""

    def __init__(self, channel: grpc.Channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeToUpdates = channel.unary_stream(
            "/max.serve.kvcache_agent.v1.KVCacheAgentService/SubscribeToUpdates",
            request_serializer=max_dot_serve_dot_kvcache__agent_dot_kvcache__agent__service__v1__pb2.SubscriptionRequest.SerializeToString,
            response_deserializer=max_dot_serve_dot_kvcache__agent_dot_kvcache__agent__service__v1__pb2.KVCacheStateUpdate.FromString,
            _registered_method=True,
        )


class KVCacheAgentServiceServicer:
    """Service that exposes the KV Cache Agent state"""

    def SubscribeToUpdates(
        self,
        request: max_dot_serve_dot_kvcache__agent_dot_kvcache__agent__service__v1__pb2.SubscriptionRequest,
        context: grpc.ServicerContext,
    ) -> Iterable[
        max_dot_serve_dot_kvcache__agent_dot_kvcache__agent__service__v1__pb2.KVCacheStateUpdate
    ]:
        """Allows subscribers to receive real-time cache state updates"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_KVCacheAgentServiceServicer_to_server(
    servicer: KVCacheAgentServiceServicer, server: grpc.Server
) -> None:
    rpc_method_handlers = {
        "SubscribeToUpdates": grpc.unary_stream_rpc_method_handler(
            servicer.SubscribeToUpdates,
            request_deserializer=max_dot_serve_dot_kvcache__agent_dot_kvcache__agent__service__v1__pb2.SubscriptionRequest.FromString,
            response_serializer=max_dot_serve_dot_kvcache__agent_dot_kvcache__agent__service__v1__pb2.KVCacheStateUpdate.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "max.serve.kvcache_agent.v1.KVCacheAgentService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "max.serve.kvcache_agent.v1.KVCacheAgentService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class KVCacheAgentService:
    """Service that exposes the KV Cache Agent state"""

    @staticmethod
    def SubscribeToUpdates(
        request: max_dot_serve_dot_kvcache__agent_dot_kvcache__agent__service__v1__pb2.SubscriptionRequest,
        target: str,
        options: Sequence[grpc.CallOption] = (),
        channel_credentials: grpc.ChannelCredentials | None = None,
        call_credentials: grpc.CallCredentials | None = None,
        insecure: bool = False,
        compression: grpc.Compression | None = None,
        wait_for_ready: bool | None = None,
        timeout: float | None = None,
        metadata: Sequence[Tuple[str, str]] | None = None,
    ) -> Iterable[
        max_dot_serve_dot_kvcache__agent_dot_kvcache__agent__service__v1__pb2.KVCacheStateUpdate
    ]:
        return grpc.experimental.unary_stream(
            request,
            target,
            "/max.serve.kvcache_agent.v1.KVCacheAgentService/SubscribeToUpdates",
            max_dot_serve_dot_kvcache__agent_dot_kvcache__agent__service__v1__pb2.SubscriptionRequest.SerializeToString,
            max_dot_serve_dot_kvcache__agent_dot_kvcache__agent__service__v1__pb2.KVCacheStateUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
