# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: max/serve/kvcache_agent/kvcache_agent_service_v1.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'max/serve/kvcache_agent/kvcache_agent_service_v1.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6max/serve/kvcache_agent/kvcache_agent_service_v1.proto\x12\x1amax.serve.kvcache_agent.v1\"\x15\n\x13SubscriptionRequest\"\xa1\x01\n\x12KVCacheStateUpdate\x12;\n\x0bupdate_type\x18\x01 \x01(\x0e\x32&.max.serve.kvcache_agent.v1.UpdateType\x12;\n\x0bmemory_tier\x18\x02 \x01(\x0e\x32&.max.serve.kvcache_agent.v1.MemoryTier\x12\x11\n\tcache_ids\x18\x03 \x03(\t*Y\n\nUpdateType\x12\x1b\n\x17UPDATE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n\x11UPDATE_TYPE_ADDED\x10\x01\x12\x17\n\x13UPDATE_TYPE_REMOVED\x10\x02*\x87\x01\n\nMemoryTier\x12\x1b\n\x17MEMORY_TIER_UNSPECIFIED\x10\x00\x12\x13\n\x0fMEMORY_TIER_GPU\x10\x01\x12\x13\n\x0fMEMORY_TIER_CPU\x10\x02\x12\x14\n\x10MEMORY_TIER_DISK\x10\x03\x12\x1c\n\x18MEMORY_TIER_OBJECT_STORE\x10\x04\x32\x90\x01\n\x13KVCacheAgentService\x12y\n\x12SubscribeToUpdates\x12/.max.serve.kvcache_agent.v1.SubscriptionRequest\x1a..max.serve.kvcache_agent.v1.KVCacheStateUpdate\"\x00\x30\x01\x42)Z\'github.com/modularml/mammoth/pkg/api/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'max.serve.kvcache_agent.kvcache_agent_service_v1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\'github.com/modularml/mammoth/pkg/api/v1'
  _globals['_UPDATETYPE']._serialized_start=273
  _globals['_UPDATETYPE']._serialized_end=362
  _globals['_MEMORYTIER']._serialized_start=365
  _globals['_MEMORYTIER']._serialized_end=500
  _globals['_SUBSCRIPTIONREQUEST']._serialized_start=86
  _globals['_SUBSCRIPTIONREQUEST']._serialized_end=107
  _globals['_KVCACHESTATEUPDATE']._serialized_start=110
  _globals['_KVCACHESTATEUPDATE']._serialized_end=271
  _globals['_KVCACHEAGENTSERVICE']._serialized_start=503
  _globals['_KVCACHEAGENTSERVICE']._serialized_end=647
# @@protoc_insertion_point(module_scope)
